---
apiVersion: v2
name: traefik
type: application
description: Traefik Proxy Helm Chart for Kubernetes
appVersion: v0.0.1
version: 0.0.1
keywords:
  - traefik
  - ingress
  - ingress-controller
dependencies:
  - name: traefik
    version: 38.0.1
    repository: https://traefik.github.io/charts